Repository asabaylus/react-command-palette, pull requests merged in 2022-08, with the labels that each got.

#1325 Build(ci) remove package-lock.json
  package-lock.json
Labels: skip-release

#1324 Build(ci): remove node v14.x from build matrix in github actions
  .github/workflows/ci.yml
  package.json
Labels: skip-release

#1300 fix: Error typo version
  package.json
Labels: bug, patch

#1332 Feat: Add displayTrigger boolean
  .gitignore
  src/__snapshots__/command-palette.test.js.snap
  src/command-palette.js
  src/command-palette.test.js
  src/index.stories.js
Labels: enhancement, minor
